title: The Workshop on<br>Democratizing Software Verification (DSV)
description: August 11, 2022<br>colocated with CAV 2022:<br>The 34th International Conference on Computer-Aided Verification
theme: jekyll-theme-cayman
github:
  is_project_page: false
